apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cdash.fullname" . }}
  labels:
    {{- include "cdash.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.cdashAdminPassword }}
  cdash-password: {{ .Values.cdashAdminPassword | b64enc | quote }}
  {{- else }}
  cdash-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
